include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "cargokit/**"
    - build/**
    - android/**
    - ios/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    - empty_container_bodies
    - initialize_in_field_declaration
    - unnecessary_const_in_enum_constructor
    - unnecessary_primary_constructor_body
    - unnecessary_type_name_in_constructor
    - use_declaring_parameters
